<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('full_name');$t->string('phone')->unique();$t->string('email')->nullable()->unique();$t->string('password');$t->timestamp('phone_verified_at')->nullable();$t->string('avatar_path')->nullable();$t->enum('status',['active','suspended'])->default('active')->index();$t->timestamp('last_login_at')->nullable();$t->rememberToken();$t->timestamps();});
  Schema::create('password_reset_tokens',function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
  Schema::create('sessions',function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
  Schema::create('personal_access_tokens',function(Blueprint $t){$t->id();$t->morphs('tokenable');$t->string('name');$t->string('token',64)->unique();$t->text('abilities')->nullable();$t->timestamp('last_used_at')->nullable();$t->timestamp('expires_at')->nullable()->index();$t->timestamps();});
  Schema::create('cache',function(Blueprint $t){$t->string('key')->primary();$t->mediumText('value');$t->integer('expiration');});Schema::create('cache_locks',function(Blueprint $t){$t->string('key')->primary();$t->string('owner');$t->integer('expiration');});
  Schema::create('jobs',function(Blueprint $t){$t->id();$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});Schema::create('job_batches',function(Blueprint $t){$t->string('id')->primary();$t->string('name');$t->integer('total_jobs');$t->integer('pending_jobs');$t->integer('failed_jobs');$t->longText('failed_job_ids');$t->mediumText('options')->nullable();$t->integer('cancelled_at')->nullable();$t->integer('created_at');$t->integer('finished_at')->nullable();});Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});
  Schema::create('notifications',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type');$t->morphs('notifiable');$t->text('data');$t->timestamp('read_at')->nullable();$t->timestamps();});
  Schema::create('otp_codes',function(Blueprint $t){$t->id();$t->string('phone')->index();$t->string('purpose')->index();$t->string('code_hash');$t->timestamp('expires_at');$t->timestamp('verified_at')->nullable();$t->unsignedTinyInteger('attempts')->default(0);$t->timestamp('resend_available_at');$t->timestamps();});
  Schema::create('user_devices',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('device_id');$t->text('fcm_token');$t->enum('platform',['android','ios']);$t->string('app_version')->nullable();$t->boolean('notifications_enabled')->default(true);$t->timestamp('last_seen_at')->nullable();$t->timestamps();$t->unique(['user_id','device_id']);});
  Schema::create('user_preferences',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->enum('locale',['ar','en'])->default('ar');$t->boolean('smart_notifications')->default(true);$t->enum('download_quality',['auto','hd','sd'])->default('auto');$t->timestamps();});
  Schema::create('academic_years',function(Blueprint $t){$t->id();$t->json('title');$t->json('subtitle')->nullable();$t->string('icon')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true)->index();$t->timestamps();});
  Schema::create('subjects',function(Blueprint $t){$t->id();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->json('title');$t->string('image_path')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true)->index();$t->timestamps();});
  Schema::create('courses',function(Blueprint $t){$t->id();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->json('title');$t->json('description');$t->string('thumbnail_path')->nullable();$t->string('hero_path')->nullable();$t->enum('status',['draft','published','archived'])->default('draft')->index();$t->boolean('is_featured')->default(false)->index();$t->timestamp('published_at')->nullable();$t->timestamps();});
  Schema::create('course_videos',function(Blueprint $t){$t->id();$t->foreignId('course_id')->constrained()->cascadeOnDelete();$t->json('title');$t->json('lesson_label')->nullable();$t->string('thumbnail_path')->nullable();$t->string('source_path');$t->string('hls_manifest_path')->nullable();$t->unsignedInteger('duration_seconds');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_preview')->default(false);$t->boolean('is_downloadable')->default(false);$t->enum('status',['processing','ready','failed'])->default('processing');$t->timestamps();});
  Schema::create('course_files',function(Blueprint $t){$t->id();$t->foreignId('course_id')->constrained()->cascadeOnDelete();$t->json('title');$t->string('file_path');$t->string('original_name');$t->string('mime_type');$t->string('extension',20);$t->unsignedBigInteger('size_bytes');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_downloadable')->default(true);$t->timestamps();});
  Schema::create('course_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('course_id')->constrained()->cascadeOnDelete();$t->enum('source',['qr','admin']);$t->timestamp('starts_at');$t->timestamp('expires_at')->nullable()->index();$t->timestamp('revoked_at')->nullable();$t->enum('status',['active','expired','revoked'])->default('active')->index();$t->timestamps();$t->unique(['user_id','course_id']);});
  Schema::create('video_progress',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('course_video_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('watched_seconds')->default(0);$t->unsignedInteger('last_position_seconds')->default(0);$t->timestamp('completed_at')->nullable();$t->timestamp('last_watched_at')->nullable();$t->timestamps();$t->unique(['user_id','course_video_id']);});
  Schema::create('subscription_qr_codes',function(Blueprint $t){$t->id();$t->foreignId('course_id')->constrained()->cascadeOnDelete();$t->string('code_hash',64)->unique();$t->string('label')->nullable();$t->timestamp('starts_at')->nullable();$t->timestamp('expires_at')->nullable();$t->unsignedInteger('max_redemptions')->default(1);$t->unsignedInteger('redemptions_count')->default(0);$t->unsignedInteger('subscription_duration_days')->nullable();$t->enum('status',['active','disabled'])->default('active');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('qr_redemptions',function(Blueprint $t){$t->id();$t->foreignId('subscription_qr_code_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('course_subscription_id')->constrained()->cascadeOnDelete();$t->timestamp('redeemed_at');$t->string('ip_address',45)->nullable();$t->string('device_identifier')->nullable();$t->timestamps();$t->unique(['subscription_qr_code_id','user_id']);});
  Schema::create('content_pages',function(Blueprint $t){$t->id();$t->string('slug')->unique();$t->json('title');$t->json('content');$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('support_requests',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('reference')->unique();$t->string('subject');$t->text('message');$t->string('category')->default('other');$t->string('attachment_path')->nullable();$t->json('device_info')->nullable();$t->enum('status',['open','in_progress','resolved','closed'])->default('open');$t->timestamps();});
 }
 public function down(): void { foreach(['support_requests','content_pages','qr_redemptions','subscription_qr_codes','video_progress','course_subscriptions','course_files','course_videos','courses','subjects','academic_years','user_preferences','user_devices','otp_codes','notifications','failed_jobs','job_batches','jobs','cache_locks','cache','personal_access_tokens','sessions','password_reset_tokens','users'] as $table) Schema::dropIfExists($table); }
};
